### ISSUE TITLE
Force closing app on android 4.4.2

### ISSUE THREAD

**Issue by kholiavko-roman** [mauron85/react-native-background-geolocation#105]
## Your Environment
* Plugin version:  0.3.0-alpha.1
* Platform: Android 
* OS version: 4.4.2
* Device manufacturer and model: ASUS 
* React Native version: 0.47.2
* Plugin configuration options: 
```
BackgroundGeolocation.configure({
      desiredAccuracy: 10,
      stationaryRadius: 25,
      distanceFilter: 25,
      debug: true,
      interval: 15000,
      stopOnStillActivity: false,
      stopOnTerminate: false,
      maxLocations: 100,
      url: AppConfig.API.postCoords + '?id=' + driverId +'&auth_key=' + token
    });
```

## Context
When I trying to start BackgroundGeolocation - app crashes. It happens on android 4.4.2 only in **release build**. In debug build all works fine ( I can started bg geolocation and it works as expected, without app crashes )

This is part from logs at the moment when I turn off bg geolocation:
```
I/com.marianhello.react.BackgroundGeolocationModule(31263): Requesting permissions from user
I/com.marianhello.bgloc.LocationService(31263): Creating LocationService
I/ReactNativeJS(31263): [DEBUG] BackgroundGeolocation started successfully
W/AccountManagerService(  551):   caller uid 10157 lacks any of android.permission.AUTHENTICATE_ACCOUNTS
D/AndroidRuntime(31263): Shutting down VM
W/dalvikvm(31263): threadid=1: thread exiting with uncaught exception (group=0x430d4140)
E/AndroidRuntime(31263): FATAL EXCEPTION: main
E/AndroidRuntime(31263): Process: com.rhino.expedite, PID: 31263
E/AndroidRuntime(31263): java.lang.RuntimeException: Unable to create service com.marianhello.bgloc.LocationService: java.lang.SecurityException: caller uid 10157 lacks any of android.permission.AUTHENTICATE_ACCOUNTS
E/AndroidRuntime(31263): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2733)
E/AndroidRuntime(31263): 	at android.app.ActivityThread.access$1800(ActivityThread.java:139)
E/AndroidRuntime(31263): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
E/AndroidRuntime(31263): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31263): 	at android.os.Looper.loop(Looper.java:149)
E/AndroidRuntime(31263): 	at android.app.ActivityThread.main(ActivityThread.java:5257)
E/AndroidRuntime(31263): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(31263): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(31263): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
E/AndroidRuntime(31263): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
E/AndroidRuntime(31263): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31263): Caused by: java.lang.SecurityException: caller uid 10157 lacks any of android.permission.AUTHENTICATE_ACCOUNTS
E/AndroidRuntime(31263): 	at android.os.Parcel.readException(Parcel.java:1465)
E/AndroidRuntime(31263): 	at android.os.Parcel.readException(Parcel.java:1419)
E/AndroidRuntime(31263): 	at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:719)
E/AndroidRuntime(31263): 	at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:613)
E/AndroidRuntime(31263): 	at com.marianhello.bgloc.sync.AccountHelper.CreateSyncAccount(AccountHelper.java:23)
E/AndroidRuntime(31263): 	at com.marianhello.bgloc.LocationService.onCreate(LocationService.java:178)
E/AndroidRuntime(31263): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2723)
E/AndroidRuntime(31263): 	... 10 more
W/ActivityManager(  551):   Force finishing activity com.rhino.expedite/.MainActivity
E/IMGSRV  (  150): :0: PVRDRMOpen: TP3, ret = 75
```

## Actual Behavior
App crashes when I turn on bg geolocation. (Only in release build)

## Steps to Reproduce
1. App started
2. Tap on the button to turn on bg geolocation

## Debug logs
Logs from release build:
https://pastebin.com/RJWXpNZ6

Logs from debug build:
https://pastebin.com/1qLwTR2x

As error is
`E/AndroidRuntime(31263): java.lang.RuntimeException: Unable to create service com.marianhello.bgloc.LocationService: java.lang.SecurityException: caller uid 10157 lacks any of android.permission.AUTHENTICATE_ACCOUNTS`

I trying add this permission to manifest
```
    <uses-permission android:name="android.permission.AUTHENTICATE_ACCOUNTS"/>
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
    <uses-permission android:name="android.permission.MANAGE_ACCOUNTS"/>
    <uses-permission android:name="android.permission.USE_CREDENTIALS"/>
```
But this does not helped me.

I found the similar problem https://github.com/mauron85/react-native-background-geolocation/issues/10
reinstall plugin form git, but I still have this problem.

**Comment by kholiavko-roman** [comment]
The same problem on Andoid 5.1.1
It works in debug builds, but crashes in release build, when I try turn on backgroun geolocation, with next message:
`W/AccountManagerService(  750):   caller uid 10211 lacks any of android.permission.AUTHENTICATE_ACCOUNTS`

Here is log:
```
D/StatusBar.NetworkController( 1104): changing data overlay icon id to 2130838448
I/ReactNativeJS(12345): ------------server successfuly answer you!
I/ReactNativeJS(12345): { success: 1 }
I/ReactNativeJS(12345): true
I/com.marianhello.react.BackgroundGeolocationModule(12345): Requesting permissions from user
I/com.marianhello.bgloc.LocationService(12345): Creating LocationService
I/ReactNativeJS(12345): [DEBUG] BackgroundGeolocation started successfully
W/AccountManagerService(  750):   caller uid 10211 lacks any of android.permission.AUTHENTICATE_ACCOUNTS
D/AndroidRuntime(12345): Shutting down VM
E/AndroidRuntime(12345): FATAL EXCEPTION: main
E/AndroidRuntime(12345): Process: com.rhino.expedite, PID: 12345
E/AndroidRuntime(12345): java.lang.RuntimeException: Unable to create service com.marianhello.bgloc.LocationService: java.lang.SecurityException: caller uid 10211 lacks any of android.permission.AUTHENTICATE_ACCOUNTS
E/AndroidRuntime(12345): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2835)
E/AndroidRuntime(12345): 	at android.app.ActivityThread.access$1800(ActivityThread.java:156)
E/AndroidRuntime(12345): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
E/AndroidRuntime(12345): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12345): 	at android.os.Looper.loop(Looper.java:211)
E/AndroidRuntime(12345): 	at android.app.ActivityThread.main(ActivityThread.java:5371)
E/AndroidRuntime(12345): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12345): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(12345): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
E/AndroidRuntime(12345): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)
E/AndroidRuntime(12345): Caused by: java.lang.SecurityException: caller uid 10211 lacks any of android.permission.AUTHENTICATE_ACCOUNTS
E/AndroidRuntime(12345): 	at android.os.Parcel.readException(Parcel.java:1553)
E/AndroidRuntime(12345): 	at android.os.Parcel.readException(Parcel.java:1505)
E/AndroidRuntime(12345): 	at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:857)
E/AndroidRuntime(12345): 	at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:662)
E/AndroidRuntime(12345): 	at com.marianhello.bgloc.sync.AccountHelper.CreateSyncAccount(AccountHelper.java:23)
E/AndroidRuntime(12345): 	at com.marianhello.bgloc.LocationService.onCreate(LocationService.java:178)
E/AndroidRuntime(12345): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2825)
E/AndroidRuntime(12345): 	... 9 more
D/ActivityManager(  750): New dropbox entry: com.rhino.expedite, data_app_crash, e5b81f36-42ed-4716-a776-d4c755e073e5
W/ActivityManager(  750):   Force finishing activity 1 com.rhino.expedite/.MainActivity
I/OpenGLRenderer(  750): Initialized EGL, version 1.4
```

@mauron85, can you help me please ?

**Comment by kholiavko-roman** [comment]
Sorry, my bad. I added in release manifest to remove this permission AUTHENTICATE_ACCOUNTS, now I removed it, and all works fine.
