### ISSUE TITLE
Notification Channel Error using >= Android 0

### ISSUE THREAD

**Issue by alexgilbertDG** [mauron85/react-native-background-geolocation#194]
This library seem's to have a problem when I use it with a Google Pixel under android 8.1.0.

The error in the adb logcat is:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.travlingbuddies, PID: 11763
                  android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I search in the code and it's seems not ready to use the new Channel API under OREO, seem's like it required a channel id to notify the user.

EXEMPLE : builder.setChannelId(ID);

react-native-mauron85-background-geolocation: 0.5.0-alpha.14

* Platform: Android
* OS version: 8.1.0
* Device manufacturer and model: Google Pixel
* React Native version: 0.51.0

**Comment by mauron85** [comment]
Upgrade your version. 0.5.0-alpha.14 is too old.

**Comment by alexgilbertDG** [comment]
I try but then I get this issue #176 , do you have a fixed on this ?

Thanks,
great work !!

**Comment by alexgilbertDG** [comment]
Can't I make it work by removing all the NotificationBuilder in java, only need to be android and don't need the notification ?

**Comment by mauron85** [comment]
Yes, but it will not work reliably in background. As service will not get promoted to foreground service.

**Comment by alexgilbertDG** [comment]
Okay, I will try updating, and will try to fix this issue #191 ! 
Thanks

**Comment by mauron85** [comment]
upgrade your version alpha 14 is too old
