### ISSUE TITLE
App suddenly start crashing when try to get location

### ISSUE THREAD

**Issue by asnad** [mauron85/react-native-background-geolocation#254]
## Your Environment

* Plugin version: 0.4.0-rc.3
* Platform: Android
* React Native version: 0.47
* Plugin configuration options: N/A
* Link to your project: N/A

## Context
Thanks for your awesome library and support. It was working good but suddenly I'm getting crashes I launch my app and when I navigate to screen where I'm using the library my app crashes but when I comment out the library all app starts working. I'm adding logs may be it will help.
## Expected Behavior
It should not crash the app
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs
07-30 14:28:17.129 20909 20909 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
07-30 14:28:17.129 20909 20909 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
07-30 14:28:17.129 20909 20909 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.biohotspot-1/base.apk"],nativeLibraryDirectories=[/data/app/com.biohotspot-1/lib/x86, /system/fake-libs, /data/app/com.biohotspot-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
07-30 14:28:17.129 20909 20909 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
07-30 14:28:17.129 20909 20909 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
07-30 14:28:17.129 20909 20909 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
07-30 14:28:17.129 20909 20909 I art     :   at void com.marianhello.bgloc.ActivityRecognitionLocationProvider.<init>(com.marianhello.bgloc.LocationService) (ActivityRecognitionLocationProvider.java:40)
07-30 14:28:17.129 20909 20909 I art     :   at com.marianhello.bgloc.LocationProvider com.marianhello.bgloc.LocationProviderFactory.getInstance(java.lang.Integer) (LocationProviderFactory.java:37)
07-30 14:28:17.129 20909 20909 I art     :   at int com.marianhello.bgloc.LocationService.onStartCommand(android.content.Intent, int, int) (LocationService.java:243)
07-30 14:28:17.129 20909 20909 I art     :   at void android.app.ActivityThread.handleServiceArgs(android.app.ActivityThread$ServiceArgsData) (ActivityThread.java:3326)
07-30 14:28:17.129 20909 20909 I art     :   at void android.app.ActivityThread.-wrap21(android.app.ActivityThread, android.app.ActivityThread$ServiceArgsData) (ActivityThread.java:-1)
07-30 14:28:17.129 20909 20909 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1582)
07-30 14:28:17.129 20909 20909 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
07-30 14:28:17.129 20909 20909 I art     :   at void android.os.Looper.loop() (Looper.java:154)
07-30 14:28:17.129 20909 20909 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6119)
07-30 14:28:17.129 20909 20909 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
07-30 14:28:17.130 20909 20909 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
07-30 14:28:17.133 20909 20909 E AndroidRuntime:  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-30 14:28:17.133 20909 20909 E AndroidRuntime:  at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-30 14:28:17.133 20909 20909 E AndroidRuntime:  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-30 14:28:17.133 20909 20909 E AndroidRuntime:  ... 12 more

07-30 14:28:17.139  1682  2843 W ActivityManager:   Force finishing activity com.biohotspot/.MainActivity

**Comment by mauron85** [comment]
Seems similar to this issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/298 Try to enable multidex

**Comment by mauron85** [comment]
Also make sure all plugins use same google play version. Here is similar issue https://github.com/react-community/react-native-maps/issues/1777

You can force plugin to use some specific google play version. Read docs https://github.com/mauron85/react-native-background-geolocation#compatibility
