### ISSUE TITLE
Unable to use the library in release APK

### ISSUE THREAD

**Issue by selyon** [mauron85/react-native-background-geolocation#354]
## Your Environment

* Plugin version: 0.5.0
* Platform: Android
* OS version: 7.0
* Device manufacturer and model:

* Running in Simulator: NO
* React Native version: 0.58.5
* Plugin configuration options:  {
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 10,
      distanceFilter: 10,
      notificationTitle: 'Background tracking',
      notificationText: 'enabled',
      debug: false,
      startOnBoot: false,
      stopOnTerminate: true,
      locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
      interval: 60000,
      stopOnStillActivity: false
    }
* Link to your project:

## Context

I created a release APK, running gradlew assembleRelease, but when i lunch the application it crashes with this error:
E/ReactNativeJS: Object is not a function (evaluating '(0,o.default)()')
E/com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mqt_native_modulescom.facebook.react.common.JavascriptException: Object is not a function (evaluating '(0,o.default)()'), stack:
    <unknown>@11:127
    _@2:1514
    d@2:897
    o@2:435
    global code@1218:4    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:194)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules

When i run the application in debug mode, installing it with react-native run-android, the application works as espected.

## Expected Behavior

The app should work when i run it

## Actual Behavior

The app crashes

## Steps to Reproduce

1. Include the library inside an application
2. run gradlew assembleRelease
3. install on device
4. run the application

**Comment by selyon** [comment]
I think is a problem related with react-native, i don't know why this library name is mentioned in the error
