### ISSUE TITLE
Link problem

### ISSUE THREAD

**Issue by joshuakoh7** [mauron85/react-native-background-geolocation#383]
RN 59.3

react-native link @mauron85/react-native-background-geolocation
```
info Linking "@mauron85/react-native-background-geolocation" iOS dependency
info iOS module "@mauron85/react-native-background-geolocation" has been successfully linked
info Linking "@mauron85/react-native-background-geolocation" Android dependency
info Android module "@mauron85/react-native-background-geolocation" has been successfully linked
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'react-native/local-cli/link/android/patches/applyPatch'
Require stack:
- M:\Google Drive\SC\frontendc\node_modules\@mauron85\react-native-background-geolocation\scripts\postlink.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (M:\Google Drive\SC\frontendc\node_modules\@mauron85\react-native-background-geolocation\scripts\postlink.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'M:\\Google ' +
      'Drive\\SC\\frontendc\\node_modules\\@mauron85\\react-native-background-geolocation\\scripts\\postlink.js'
  ]
}
M:\Google Drive\SC\frontendc\node_modules\@react-native-community\cli\build\tools\getHooks.js:37
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node node_modules/@mauron85/react-native-background-geolocation/scripts/postlink.js" command
    at ChildProcess.<anonymous> (M:\Google Drive\SC\frontendc\node_modules\@react-native-community\cli\build\tools\getHooks.js:37:15)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by joshuakoh7** [comment]
Same as #364 but the patch didn't solve it

**Comment by maratumba** [comment]
Experiencing this issue today on a fresh react-native app.
```
OS: Windows (10.0.19044 Build 19044)
node: 18.14.1
react-native: 0.71.3
@react-native-community/cli-platform-android: 10.1.3
react-native-background-geolocation: 0.6.3
```

```
PS C:\Users\username\dev\ReactNativeApp> node ./node_modules/@mauron85/react-native-background-geolocation/scripts/postlink.js
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '@react-native-community/cli-platform-android/build/link/patches/applyPatch'       
Require stack:
- C:\Users\username\dev\ReactNativeApp\node_modules\@mauron85\react-native-background-geolocation\scripts\postlink.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\username\dev\ReactNativeApp\node_modules\@mauron85\react-native-background-geolocation\scripts\postlink.js:14:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\username\\dev\\ReactNativeApp\\node_modules\\@mauron85\\react-native-background-geolocation\\scripts\\postlink.js'
  ]
}
```

Checking, indeed, there is no `patches` under `cli-platform-android/build/link`:
```
PS C:\Users\username\dev\ReactNativeApp> ls .\node_modules\@react-native-community\cli-platform-android\build\link\patches

ls .\node_modules\@react-native-community\cli-platform-android\build\link\patches\
ls : Cannot find path 'C:\Users\gulyamani\dev\RescueCoordinator\node_modules\@react-native-community\cli-pla 
tform-android\build\link\patches\' because it does not exist.
At line:1 char:1
+ ls .\node_modules\@react-native-community\cli-platform-android\build\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\gulyam...d\link\patches\:String) [Get-ChildItem], I  
   temNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```
