### ISSUE TITLE
Fatal error using example code

### ISSUE THREAD

**Issue by joshuakoh7** [mauron85/react-native-background-geolocation#384]
## Your Environment

* Plugin version: 0.5.3
* Platform: Android
* OS version: Pie
* Device manufacturer and model: Huawei

* Running in Simulator: No
* React Native version: 59.3
* Plugin configuration options: 
* Link to your project: 

## Context
Using the example code in readme causes the app to terminate

## Expected Behavior
App should run

## Actual Behavior
App crashes

## Steps to Reproduce

1. Add code under "Quick example" to project
2. App loads then crashes

## Debug logs

adb logcat output:
```
06-25 12:14:27.162  7232  7232 E AndroidRuntime: FATAL EXCEPTION: main
06-25 12:14:27.162  7232  7232 E AndroidRuntime: Process: com.frontendc, PID: 7232
06-25 12:14:27.162  7232  7232 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at com.marianhello.bgloc.provider.LocationProviderFactory.getInstance(LocationProviderFactory.java:37)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at com.marianhello.bgloc.service.LocationServiceImpl.start(LocationServiceImpl.java:348)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at com.marianhello.bgloc.service.LocationServiceImpl.processCommand(LocationServiceImpl.java:303)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at com.marianhello.bgloc.service.LocationServiceImpl.onStartCommand(LocationServiceImpl.java:285)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4158)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at android.app.ActivityThread.access$2400(ActivityThread.java:267)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:109)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7470)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.frontendc-MzSHYrsi9VsfVU68DPZ9Yg==/base.apk"],nativeLibraryDirectories=[/data/app/com.frontendc-MzSHYrsi9VsfVU68DPZ9Yg==/lib/arm64, /data/app/com.frontendc-MzSHYrsi9VsfVU68DPZ9Yg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-25 12:14:27.162  7232  7232 E AndroidRuntime: 	... 13 more
06-25 12:14:27.163  1267  7609 W DropBoxManagerService: Dropping: data_app_crash (1928 > 0 bytes)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mainjava.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.marianhello.bgloc.provider.LocationProviderFactory.getInstance(LocationProviderFactory.java:37)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.marianhello.bgloc.service.LocationServiceImpl.start(LocationServiceImpl.java:348)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.marianhello.bgloc.service.LocationServiceImpl.processCommand(LocationServiceImpl.java:303)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.marianhello.bgloc.service.LocationServiceImpl.onStartCommand(LocationServiceImpl.java:285)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4158)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.app.ActivityThread.access$2400(ActivityThread.java:267)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.os.Handler.dispatchMessage(Handler.java:109)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.os.Looper.loop(Looper.java:207)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.app.ActivityThread.main(ActivityThread.java:7470)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Native Method)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.frontendc-MzSHYrsi9VsfVU68DPZ9Yg==/base.apk"],nativeLibraryDirectories=[/data/app/com.frontendc-MzSHYrsi9VsfVU68DPZ9Yg==/lib/arm64, /data/app/com.frontendc-MzSHYrsi9VsfVU68DPZ9Yg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-25 12:14:27.165  7232  7232 E com.marianhello.logging.UncaughtExceptionLogger: 	... 13 common frames omitted
```

**Comment by joshuakoh7** [comment]
Solved this by manually specifying play service version to be used

**Comment by mthuong** [comment]
> Solved this by manually specifying play service version to be used

Which play service version did you use? @joshuakoh7
