### ISSUE TITLE
react-native link installation fails

### ISSUE THREAD

**Issue by nene** [mauron85/react-native-background-geolocation#386]
## Your Environment
* Plugin version: 0.5.3
* Platform: MacOS Mojave 10.14.5
* React Native version: 0.59.5
* Plugin configuration options: none
* Link to your project: Sorry, it's private.

## Context
After installing the library, I tried to link it using `react-native link` as suggested in README.

## Expected Behavior
I expect the linking to finish successfully.

## Actual Behavior
It ends with a crash:
```
$ react-native link @mauron85/react-native-background-geolocation
info Linking "@mauron85/react-native-background-geolocation" iOS dependency
info iOS module "@mauron85/react-native-background-geolocation" has been successfully linked
info Linking "@mauron85/react-native-background-geolocation" Android dependency
info Android module "@mauron85/react-native-background-geolocation" has been successfully linked
module.js:550
    throw err;
    ^

Error: Cannot find module 'react-native/local-cli/link/android/patches/applyPatch'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-app/node_modules/@mauron85/react-native-background-geolocation/scripts/postlink.js:14:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
/my-app/node_modules/@react-native-community/cli/build/tools/getHooks.js:37
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node node_modules/@mauron85/react-native-background-geolocation/scripts/postlink.js" command
    at ChildProcess.commandProcess.on.code (/my-app/node_modules/@react-native-community/cli/build/tools/getHooks.js:37:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error Command failed with exit code 1.
```

## Steps to Reproduce
```
yarn add @mauron85/react-native-background-geolocation
react-native link @mauron85/react-native-background-geolocation
```

## Context
I want to test out this library :)

## Possible causes
It might be that there's a conflict with the other background-geolocation library that I'm using: https://github.com/transistorsoft/react-native-background-geolocation

I haven't yet tried to first uninstall that and then install this lib. Similarly I haven't tried the installation of this lib in completely clean project.

**Comment by bilsak18** [comment]
Same error !!!

**Comment by mauron85** [comment]
Yes, react native switch to different linking mechanism. Plugin needs to be adjusted.

**Comment by mauron85** [comment]
Relevant discussion https://github.com/mauron85/react-native-background-geolocation/pull/374

**Comment by digDev2019** [comment]
Please tell me in more detail, how to do manual linking
