### ISSUE TITLE
Service is shutdowning on app start

### ISSUE THREAD

**Issue by sefatunckanat** [mauron85/react-native-background-geolocation#404]

**Comment by takdemir** [comment]
Same problem. BackgroundGeolocation.start() closes the android app

**Comment by sefatunckanat** [comment]
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm; at com.marianhello.bgloc.provider.LocationProviderFactory.getInstance(LocationProviderFactory.java:37) at com.marianhello.bgloc.service.LocationServiceImpl.start(LocationServiceImpl.java:348) at com.marianhello.bgloc.service.LocationServiceImpl.processCommand(LocationServiceImpl.java:303) at com.marianhello.bgloc.service.LocationServiceImpl.onStartCommand(LocationServiceImpl.java:285) at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3738) at android.app.ActivityThread.access$1700(ActivityThread.java:201) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:207) at android.app.ActivityThread.main(ActivityThread.java:6867) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.localreminder-NXm-DoeBwiiZpOiX0AzByw==/base.apk"],nativeLibraryDirectories=[/data/app/com.localreminder-NXm-DoeBwiiZpOiX0AzByw==/lib/arm64, /data/app/com.localreminder-NXm-DoeBwiiZpOiX0AzByw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) ... 13 more
```

#384 

i think same error. 

@mauron85 @joshuakoh7 help :(

**Comment by JohnTheo13** [comment]
@sefatunckanat make sure that that the new BackgroundGeolocationPackage() comes directly after the MainReactPackage()
```
return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new BackgroundGeolocationPackage(),
```

**Comment by mrben1985** [comment]
Anyone made any progress on this? I have a brand new install and every time I call the start I get the stopped message.

**Comment by takdemir** [comment]
I don't use that module any more. I solved with "react-native-background-timer". Also, "react-native-background-task" is a good alternative.

**Comment by mauron85** [comment]
@sefatunckanat your adb dump literally mention problem with google play libraries. Recommend to check those. If they're present, ...

**Comment by mauron85** [comment]
Also regarding your first debug log. I suggest you to remove all plugins and try to run only this one to see if it still crashes. Because I don't see any specific error related to this plugin.

**Comment by jonasgroendahl** [comment]
Same problem here, installed latest version of react-native-maps and it starts crashed upon load

**Comment by srivatsav** [comment]
@sefatunckanat please check if the dependency `com.google.android.gms:play-services-location:17.0.0` is included n your app/build.gradle file. If not, Adding this should fix it.

**Comment by thaiphamvan** [comment]
@srivatsav Thanks.
