### ISSUE TITLE
Service not registered

### ISSUE THREAD

**Issue by davidstoneham** [mauron85/react-native-background-geolocation#46]
I am unable to replicate this issue but i am receiving this error on the production version of this app for some of my users.

`
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.marianhello.react.BackgroundGeolocationModule$1@24a2165
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1048)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1323)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
       at com.marianhello.react.BackgroundGeolocationModule.doUnbindService(BackgroundGeolocationModule.java:502)
       at com.marianhello.react.BackgroundGeolocationModule.stop(BackgroundGeolocationModule.java:286)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:234)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
`

**Comment by nordved** [comment]
I get the same error on my emulator. I also can't reproduce or provoke it, but it happens *sometimes*.

**Comment by JimmyDaddy** [comment]
I got the same error through my Android users too. 
Here is the output:
```
java.lang.RuntimeException: Unable to destroy activity {com.sxc.songxiaofu.captain/com.sxc.songxiaofu.captain.MainActivity}: java.lang.IllegalArgumentException: Service not registered: com.marianhello.react.BackgroundGeolocationModule$1@422036c0
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3496)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3514)
	at android.app.ActivityThread.access$1400(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5105)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Service not registered: com.marianhello.react.BackgroundGeolocationModule$1@422036c0
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:926)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1652)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:529)
	at com.marianhello.react.BackgroundGeolocationModule.doUnbindService(BackgroundGeolocationModule.java:502)
	at com.marianhello.react.BackgroundGeolocationModule.onHostDestroy(BackgroundGeolocationModule.java:105)
	at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:205)
	at com.facebook.react.XReactInstanceManagerImpl.moveToBeforeCreateLifecycleState(XReactInstanceManagerImpl.java:607)
	at com.facebook.react.XReactInstanceManagerImpl.onHostDestroy(XReactInstanceManagerImpl.java:539)
	at com.facebook.react.XReactInstanceManagerImpl.onHostDestroy(XReactInstanceManagerImpl.java:546)
	at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:128)
	at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:72)
	at android.app.Activity.performDestroy(Activity.java:5403)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3483)
	... 11 more
java.lang.IllegalArgumentException: Service not registered: com.marianhello.react.BackgroundGeolocationModule$1@422036c0
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:926)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1652)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:529)
	at com.marianhello.react.BackgroundGeolocationModule.doUnbindService(BackgroundGeolocationModule.java:502)
	at com.marianhello.react.BackgroundGeolocationModule.onHostDestroy(BackgroundGeolocationModule.java:105)
	at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:205)
	at com.facebook.react.XReactInstanceManagerImpl.moveToBeforeCreateLifecycleState(XReactInstanceManagerImpl.java:607)
	at com.facebook.react.XReactInstanceManagerImpl.onHostDestroy(XReactInstanceManagerImpl.java:539)
	at com.facebook.react.XReactInstanceManagerImpl.onHostDestroy(XReactInstanceManagerImpl.java:546)
	at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:128)
	at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:72)
	at android.app.Activity.performDestroy(Activity.java:5403)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3483)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3514)
	at android.app.ActivityThread.access$1400(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5105)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 228 days. You may reopen this issue if it has been closed in error.

**Comment by tjadli** [comment]
I am still getting this error, did anyone find any solution ? 
PS: i am on RN49

**Comment by thtRajasthaniGuy** [comment]
same issue
