### ISSUE TITLE
Could not resolve all dependencies for configuration ':app:_debugApk'

### ISSUE THREAD

**Issue by satishmane** [mauron85/react-native-background-geolocation#52]
Hi,
I have done react-native setup and have successfully running other android react-native apps.

But In my react-native project, I just insalled npm install react-native-mauron85-background-geolocation --save
then added as below

In android/settings.gradle

include ':react-native-mauron85-background-geolocation', ':app'
project(':react-native-mauron85-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mauron85-background-geolocation/android')

In android/app/build.gradle

dependencies {
...
compile project(':react-native-mauron85-background-geolocation')
...
}

Registered Module in MainApplication.java
import com.marianhello.react.BackgroundGeolocationPackage; // <--- Import Package
@Override
protected List getPackages() {
return Arrays.asList(
new MainReactPackage(),
new BackgroundGeolocationPackage() // <---- Add the Package
);
}

then I ran react-native run-android, it fails with below error

Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':app'.
Could not resolve all dependencies for configuration ':app:_debugApk'.
Configuration with name 'default' not found.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Total time: 5.074 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

Can you please help understand whats wrong

**Comment by satishmane** [comment]
Issue got resolved after adding 'lib' after android.
project(':react-native-mauron85-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mauron85-background-geolocation/android/lib')

**Comment by Gopinath7007** [comment]
In which file i need to made changes

**Comment by satishmane** [comment]
settings.gradle under android folder

**Comment by muhammadridho** [comment]
Hai, satishmane.
Have you checked all the dependencies of your android project, located in the android folder, inside there is the settings.gradle file. In this file every dependencies of your project will be checked.

example :
include 'your dependencies'
project(':your dependencies').projectDir = new File('path dependencies')

**Comment by edimdendidiwangga** [comment]
yang bener do 💃 🏃

**Comment by KrisRoofe** [comment]
stackoverflow question [Could not resolve all dependencies for configuration ':app:_debugApkCopy'](https://stackoverflow.com/q/41387085/6521116)

**Comment by matthewvedder** [comment]
Try removing the contents of android/app/build.gradle and rebuilding.

**Comment by imanshu1** [comment]
simply run $ npm i and it will work :)

**Comment by luisfuertes** [comment]
I have this issue.

I have tried to run npm i but it doesnt work

**Comment by luisfuertes** [comment]
Same issue here.

**Versions:**
```
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-background-geolocation": "0.4.1"
```

**Stack trace**
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':app:_debugApk'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:70)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolve(ErrorHandlingConfigurationResolver.java:45)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:372)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:347)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:340)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at com.android.build.gradle.internal.DependencyManager.collectArtifacts(DependencyManager.java:497)
        at com.android.build.gradle.internal.DependencyManager.gatherDependencies(DependencyManager.java:375)
        at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.java:278)
        at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.java:155)
        at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.java:364)
        at com.android.build.gradle.internal.VariantManager$9.call(VariantManager.java:636)
        at com.android.build.gradle.internal.VariantManager$9.call(VariantManager.java:633)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.java:44)
        at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:629)
        at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:823)
        at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:494)
        at com.android.build.gradle.internal.VariantManager$1.call(VariantManager.java:269)
        at com.android.build.gradle.internal.VariantManager$1.call(VariantManager.java:266)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:265)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:688)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy10.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
        ... 52 more
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'default' not found.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:92)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:229)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:82)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:37)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:69)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.ProjectIvyDependencyDescriptorFactory.createDependencyDescriptor(ProjectIvyDependencyDescriptorFactory.java:40)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependencyDescriptorFactory.createDependencyDescriptor(DefaultDependencyDescriptorFactory.java:35)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependenciesToModuleDescriptorConverter.addDependencies(DefaultDependenciesToModuleDescriptorConverter.java:43)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependenciesToModuleDescriptorConverter.addDependencyDescriptors(DefaultDependenciesToModuleDescriptorConverter.java:36)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.DefaultConfigurationComponentMetaDataBuilder.addDependencies(DefaultConfigurationComponentMetaDataBuilder.java:51)
        at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.DefaultConfigurationComponentMetaDataBuilder.addConfigurations(DefaultConfigurationComponentMetaDataBuilder.java:39)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.toRootComponentMetaData(DefaultConfiguration.java:557)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$DefaultResolveContextToComponentResolver.resolve(DefaultArtifactDependencyResolver.java:144)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:74)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$1.execute(DefaultArtifactDependencyResolver.java:90)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$1.execute(DefaultArtifactDependencyResolver.java:80)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:80)
        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:41)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:64)
        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolve(DefaultConfigurationResolver.java:91)
        at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyConfigurationResolver.resolve(SelfResolvingDependencyConfigurationResolver.java:40)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolve(ShortCircuitEmptyConfigurationResolver.java:52)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolve(ErrorHandlingConfigurationResolver.java:43)
        ... 92 more
```

**Comment by isflo96** [comment]
Hi some one can help me with this issue ?


PS C:\Users\Israel Flores\Documents\GitHub\Curso Udemy Ionic\Pruebas> ionic cordova build android
Running app-scripts build: --platform android --target cordova
[09:03:57]  build dev started ...
[09:03:57]  clean started ...
[09:03:57]  clean finished in 6 ms
[09:03:57]  copy started ...
[09:03:57]  deeplinks started ...
[09:03:57]  deeplinks finished in 27 ms
[09:03:57]  transpile started ...
[09:04:00]  transpile finished in 3.27 s
[09:04:00]  preprocess started ...
[09:04:00]  preprocess finished in 1 ms
[09:04:00]  webpack started ...
[09:04:01]  copy finished in 3.47 s
[09:04:08]  webpack finished in 7.87 s
[09:04:08]  sass started ...
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
[09:04:09]  sass finished in 895 ms
[09:04:09]  postprocess started ...
[09:04:09]  postprocess finished in 6 ms
[09:04:09]  lint started ...
[09:04:09]  build dev finished in 12.22 s
> cordova build android
Android Studio project detected

ANDROID_HOME=C:\Users\Israel Flores\AppData\Local\Android\Sdk\
JAVA_HOME=C:\Program Files\java\jdk1.8.0_151
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_cdbyow7qc6mpzabpg36j9y05b.run(C:\Users\Israel Flores\Documents\GitHub\Curso Udemy Ionic\Pruebas\platforms\android\app\build.gradle:144)
[09:04:14]  lint finished in 4.34 s
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild
 UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources
 UP-TO-DATE
:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources

:CordovaLib:generateDebugSources
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug

:app:preBuild UP-TO-DATE
:app:preDebugBuild
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :barcodescanner:.
  Searched in the following locations:
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/m2repository//barcodescanner//barcodescanner-.pom
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/m2repository//barcodescanner//barcodescanner-.aar
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/google/m2repository//barcodescanner//barcodescanner-.pom
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/google/m2repository//barcodescanner//barcodescanner-.aar
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/android/m2repository//barcodescanner//barcodescanner-.pom
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/android/m2repository//barcodescanner//barcodescanner-.aar
      https://jcenter.bintray.com//barcodescanner//barcodescanner-.pom
      https://jcenter.bintray.com//barcodescanner//barcodescanner-.aar
      https://maven.google.com//barcodescanner//barcodescanner-.pom
      https://maven.google.com//barcodescanner//barcodescanner-.aar
      https://repo1.maven.org/maven2//barcodescanner//barcodescanner-.pom
      https://repo1.maven.org/maven2//barcodescanner//barcodescanner-.aar
      file:/C:/Users/Israel Flores/Documents/GitHub/Curso Udemy Ionic/Pruebas/platforms/android/app/libs/barcodescanner-.aar
      file:/C:/Users/Israel Flores/Documents/GitHub/Curso Udemy Ionic/Pruebas/platforms/android/app/libs/barcodescanner.aar
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

14 actionable tasks: 4 executed, 10 up-to-date
(node:14692) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1
Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :barcodescanner:.
  Searched in the following locations:
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/m2repository//barcodescanner//barcodescanner-.pom
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/m2repository//barcodescanner//barcodescanner-.aar
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/google/m2repository//barcodescanner//barcodescanner-.pom
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/google/m2repository//barcodescanner//barcodescanner-.aar
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/android/m2repository//barcodescanner//barcodescanner-.pom
      file:/C:/Users/Israel Flores/AppData/Local/Android/Sdk/extras/android/m2repository//barcodescanner//barcodescanner-.aar
      https://jcenter.bintray.com//barcodescanner//barcodescanner-.pom
      https://jcenter.bintray.com//barcodescanner//barcodescanner-.aar
      https://maven.google.com//barcodescanner//barcodescanner-.pom
      https://maven.google.com//barcodescanner//barcodescanner-.aar
      https://repo1.maven.org/maven2//barcodescanner//barcodescanner-.pom
      https://repo1.maven.org/maven2//barcodescanner//barcodescanner-.aar
      file:/C:/Users/Israel Flores/Documents/GitHub/Curso Udemy Ionic/Pruebas/platforms/android/app/libs/barcodescanner-.aar
      file:/C:/Users/Israel Flores/Documents/GitHub/Curso Udemy Ionic/Pruebas/platforms/android/app/libs/barcodescanner.aar
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
(node:14692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mauron85** [comment]
@isflo96 your issue is not related to this plugin. Your error message literally says:

>Could not find :barcodescanner:.

**Comment by TunvirRahman** [comment]
"react-native upgrade" solved my problem.

**Comment by cyphire** [comment]
just in case someone sees this and doesn't need to go crazy...

I get this after installing a package in npm...

I close the node window, as suggested above run "npm i"

Then rebuild... Goes away!

p.s. Always close your node window BEFORE installing a new package....

**Comment by bashirpour** [comment]
Make sure your internet connection and if use vpn check vpn connection is ok

**Comment by AndreyPatseiko** [comment]
Me is helped this solution
![image](https://user-images.githubusercontent.com/18285745/41127177-afee2526-6ab2-11e8-9638-874e525e5758.png)

**Comment by Edison4mobile** [comment]
@TunvirRahman .... perfect thanks.

**Comment by agunbuhori** [comment]
```bash
react-native upgrade
```

Solved my problem

**Comment by EugenePizzerbert** [comment]
remove build file

**Comment by GabrielScalici** [comment]
install npm again:
$npm install

**Comment by imanshu1** [comment]
What you need to do is
1.) Go to your project location **remove the node modules folder**
2.) **run npm install** 

and it will work

**Comment by anubhav19rai** [comment]
Please run this command **react-native upgrade**. This command will ask replace existing file or not. If you    want to replace a particular file press Y and hit enter button or press N. After completing this command than run command  **react-native link**. This command will link all dependencies than you can run command **react native run-android /ios**. This issue create when you uninstall some dependencies so sometimes  it do not update build files like setting.gradle build.gradle etc.

**Comment by MrIceman** [comment]
Go to your Apps build.gradle file and put within "repositories" and "allprojects" the repository google() on the first place

->  repositories {
        google()
        jcenter()
    }
-> 
allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
