### ISSUE TITLE
Unable to create service com.marianhello.bgloc.service.LocationServiceImpl: java.lang.SecurityException: uid 10293 cannot explicitly add accounts of type: xx.xx.xx.mauron85.bgloc.account

### ISSUE THREAD

**Issue by abraham-rose** [mauron85/react-native-background-geolocation#529]
## Your Environment

* Plugin version: 0.6.3
* Platform: Android
* OS version: 10
* Device manufacturer and model: Realme, realme X

* Running in Simulator: No
* React Native version: 0.62.2
* Plugin configuration options: 
{
      desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
      stationaryRadius: 10,
      distanceFilter: 0,
      debug: false,
      startOnBoot: false,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
      interval: 60000,
      fastestInterval: 60000,
      activitiesInterval: 60000,
      stopOnStillActivity: false,
      url: url-link-here,
      httpHeaders: {
        auth_header: token,
        'api-key': API_KEY,
      },
      postTemplate: {
         geoLocation: {
             latitude: '@latitude',
             longitude: '@longitude',
             accuracy: '@accuracy',
         },
         time: '@time',
         network: '@provider', // Implemented using location transform
      },
    }
* Link to your project:

## Context

The issue was found in the Firebase crashlytics for the application in production. It was found only in one user who uses realme device. 
Brand: Realme
Model: realme X
Operating System
Version: 10

## Expected Behavior

No crashes to happen for the realme X user

## Actual Behavior

Attaching the stack traces from crashlytics.

Fatal Exception: java.lang.RuntimeException: Unable to create service com.marianhello.bgloc.service.LocationServiceImpl: java.lang.SecurityException: uid 10293 cannot explicitly add accounts of type: xx.xx.xx.mauron85.bgloc.account
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4226)
       at android.app.ActivityThread.access$200(ActivityThread.java:240)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2081)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:228)
       at android.app.ActivityThread.main(ActivityThread.java:7782)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

Caused by java.lang.SecurityException: uid 10293 cannot explicitly add accounts of type: xx.xx.xx.mauron85.bgloc.account
       at android.os.Parcel.createException(Parcel.java:2087)
       at android.os.Parcel.readException(Parcel.java:2055)
       at android.os.Parcel.readException(Parcel.java:2003)
       at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:1660)
       at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:889)
       at com.marianhello.bgloc.sync.AccountHelper.CreateSyncAccount(AccountHelper.java:24)
       at com.marianhello.bgloc.service.LocationServiceImpl.onCreate(LocationServiceImpl.java:192)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4214)
       at android.app.ActivityThread.access$200(ActivityThread.java:240)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2081)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:228)
       at android.app.ActivityThread.main(ActivityThread.java:7782)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

Caused by android.os.RemoteException: Remote stack trace:
at com.android.server.accounts.AccountManagerService.addAccountExplicitlyWithVisibility(AccountManagerService.java:480)
	at com.android.server.accounts.AccountManagerService.addAccountExplicitly(AccountManagerService.java:1646)
	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:630)
	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1082)
	at android.os.Binder.execTransactInternal(Binder.java:1021)

## Steps to Reproduce

Unable to reproduce from our end.

## Context

This bug has affected the realme x user 77 times over a duration of 7 days. The crashes seems to be happening 8% background as per the crashlytics data.

**Comment by dcoellarb** [comment]
Same problem here, any solution?

**Comment by chungweileong94** [comment]
I faced the same issue, apparently, this basically means that the device already has an account with the same account type.
The good news is you can actually overwrite the default account type in `build.gradle`.

```
defaultConfig {
        ...
        resValue "string", "mauron85_bgloc_account_type", "${applicationId}.${applicationIdSuffix}.mauron85.bgloc.account"
}
```

**Comment by Mehuge** [comment]
I have same issue. Makes no difference if I use `.account` or `.mauron85.bgloc.account` as the suffix, crashes in the same way.
