### ISSUE TITLE
Unable to start service 

### ISSUE THREAD

**Issue by JimmyDaddy** [mauron85/react-native-background-geolocation#59]
## Your Environment
* Plugin version: 0.2.0-alpha.6
* Platform:  Android
* OS version: 5.1.1
* React Native version:0.34
* Plugin configuration options: 

## Context
```
java.lang.RuntimeException: Unable to start service com.marianhello.bgloc.LocationService@33bd9b8e with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.marianhello.bgloc.Config.getStopOnTerminate()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3124)
	at android.app.ActivityThread.access$2100(ActivityThread.java:176)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:5619)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:976)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.marianhello.bgloc.Config.getStopOnTerminate()' on a null object reference
	at com.marianhello.bgloc.LocationService.onTaskRemoved(LocationService.java:200)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3109)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.marianhello.bgloc.Config.getStopOnTerminate()' on a null object reference
	at com.marianhello.bgloc.LocationService.onTaskRemoved(LocationService.java:200)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3109)
	at android.app.ActivityThread.access$2100(ActivityThread.java:176)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:5619)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:976)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
```

**Comment by mauron85** [comment]
Yes, this seems to be bug. Can you please add steps how to reproduce this?

**Comment by JimmyDaddy** [comment]
@mauron85 I'm sorry, I can't reproduce this,  all my test device run my app are ok. This was reported from my app's user's device, and only one produce this bug.
Here is the bug report：
https://bughd.com/share/issue/88a78007a58c8035dc40f6c5ff17b658

**Comment by Misioka** [comment]
I have same problem do you solve it somehow @JimmyDaddy please?

**Comment by JimmyDaddy** [comment]
@Misioka sorry, I'm not using this plugin now, I'm using another one

**Comment by sarju-leuwint** [comment]
com.marianhello.react.BackgroundGeolocationModule: Configuration error: Attempt to invoke virtual method 'android.content.Context android.content.ContextWrapper.getApplicationContext()' on a null object reference

I am doing Start Background Geo Location based on the background timer scheduler. But when the app closed and start the backgorund geo location , we got above error.
