### ISSUE TITLE
Module crashes on android devices

### ISSUE THREAD

**Issue by maluramichael** [mauron85/react-native-background-geolocation#69]
Some of our users said our app crashes after a couple of seconds. The only info i got is the following exception from fabric.

```
Fatal Exception: java.lang.NullPointerException
       at android.content.ComponentName.<init>(ComponentName.java:77)
       at android.content.Intent.<init>(Intent.java:4334)
       at com.marianhello.react.BackgroundGeolocationModule.startBackgroundService(BackgroundGeolocationModule.java:249)
       at com.marianhello.react.BackgroundGeolocationModule.startAndBindBackgroundService(BackgroundGeolocationModule.java:241)
       at com.marianhello.react.BackgroundGeolocationModule.start(BackgroundGeolocationModule.java:215)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
       at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(NativeRunnableDeprecated.java)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:146)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 210 days. You may reopen this issue if it has been closed in error.
