### ISSUE TITLE
Background Service stops (stopOnTerminate `true` doesn't work)

### ISSUE THREAD

**Issue by L3V147H4N** [mauron85/react-native-background-geolocation#90]
using RN 0.43.3 on android 7.0 and 6.0 (Sony & Motorola)
when stopOnTerminate is set to `true` the service crashes when I close the app

this is all I could find in the logcat

`java.lang.RuntimeException: Unable to destroy activity {com.guardianst/com.guardianst.MainActivity}: java.lang.IllegalArgumentException: Service not registered: com.marianhello.react.BackgroundGeolocationModule$1@ace0e42
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4280)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4298)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.ActivityThread.-wrap6(ActivityThread.java)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:241)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6217)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
07-05 08:59:03.838  8571  8571 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Service not registered: com.marianhello.react.BackgroundGeolocationModule$1@ace0e42
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1290)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.ContextImpl.unbindService(ContextImpl.java:1484)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.marianhello.react.BackgroundGeolocationModule.doUnbindService(BackgroundGeolocationModule.java:502)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.marianhello.react.BackgroundGeolocationModule.onHostDestroy(BackgroundGeolocationModule.java:105)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:236)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState(ReactInstanceManager.java:651)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:575)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:588)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:142)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:72)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.Activity.performDestroy(Activity.java:6907)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4267)
07-05 08:59:03.838  8571  8571 E AndroidRuntime:        ... 9 more`

**Comment by L3V147H4N** [comment]
is there a fix for this?

**Comment by L3V147H4N** [comment]
NullPointerException

`09-19 17:24:32.222  3215  3244 E AndroidRuntime: Process: com.guardianst, PID: 3215
09-19 17:24:32.222  3215  3244 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at android.content.ComponentName.<init>(ComponentName.java:128)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at android.content.Intent.<init>(Intent.java:4449)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at com.marianhello.react.BackgroundGeolocationModule.stopBackgroundService(BackgroundGeolocationModule.java:462)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at com.marianhello.react.BackgroundGeolocationModule.stop(BackgroundGeolocationModule.java:287)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
09-19 17:24:32.222  3215  3244 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
09-19 17:24:32.275  1537  3061 I OpenGLRenderer: Initialized EGL, version 1.4
09-19 17:24:32.280  1537  3061 D EGL_emulation: eglCreateContext: 0x7f566b792fa0: maj 2 min 0 rcv 2
09-19 17:24:32.286  1537  3061 D EGL_emulation: eglMakeCurrent: 0x7f566b792fa0: ver 2 0 (tinfo 0x7f566ae66aa0)
09-19 17:24:32.315  1537  3061 E EGL_emulation: tid 3061: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
09-19 17:24:32.315  1537  3061 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7f566ae07640, error=EGL_BAD_MATCH
09-19 17:24:32.316  1537  3061 D EGL_emulation: eglMakeCurrent: 0x7f566b792fa0: ver 2 0 (tinfo 0x7f566ae66aa0)
09-19 17:24:33.731  1644  2062 D EGL_emulation: eglMakeCurrent: 0x7f567074e840: ver 2 0 (tinfo 0x7f56706ef360)
`

**Comment by L3V147H4N** [comment]
I started a fresh project and everything is working fine, it seems for some reason my previous project got corrupt somehow and I don't exactly know what's wrong
